nav:
  - Advent of the Haelborne: index.md
  - Prologue | Eating New People: Prologue.md
  - CH1 | Everything Stops: CH1.md
  - CH2 | Vacation...?: CH2.md
  - CH3 | Crab Rider: CH3.md
  - CH4 | You Can Call Me...: CH4.md
  - CH5 | MacGuffins and Morons: CH5.md
  - CH6 | Advanced Interrogation Tactics: CH6.md
  - CH7 | Grim Hasn't Even Caught Up Yet!: CH7.md
  - CH8 | Burger Barn: CH8.md
  - CH9 | Big Bad Goat: CH9.md
  - CH10 | Dish Soap Devil: CH10.md
  - CH11 | Knock, Knock: CH11.md
  - CH12 | Deadbeat Businessman: CH12.md
  - CH13 | Glory to Rattesse: CH13.md
  - CH14 | Lloyden lastName: CH14.md
  - CH15 | Strange Glow: CH15.md
  - CH16 | We Need To Talk: CH16.md
  - CH17 | We Get To Talk: CH17.md
  - CH18 | Your Parents Fucking Suck: CH18.md
  - CH19 | Twisted Little Hearts: CH19.md
  - CH20 | Can I Pet That Dog?: CH20.md
  - CH21 | Discussing the Belly: CH21.md
  - CH22 | Limned in Flame: CH22.md